d <- "D:/学习资料/大三上/生物信息学/EasyMultiProfiler-Web/.local_run/data/projects/session_owners"
cat("dir exists:", dir.exists(d), "\n")
f1 <- file.path(d, "aaa_overwrite_test.json")
writeLines("1", f1)
tmp <- tempfile(".emp-json-", tmpdir = d)
cat("tmp file created by tempfile on disk:", file.exists(tmp), "\n")
writeLines("2", tmp)
r <- file.rename(tmp, f1)
cat("rename(existing dest) result:", r, "\n")
cat("dest content now:", paste(readLines(f1), collapse = ","), "\n")
unlink(f1)
f2 <- file.path(d, "aaa_new_test.json")
tmp2 <- tempfile(".emp-json-", tmpdir = d)
writeLines("3", tmp2)
cat("rename(new dest) result:", file.rename(tmp2, f2), "\n")
unlink(f2)
cat("R.version:", as.character(getRversion()), "\n")
